"""Generate a .env file with a fresh Fernet key and JWT secret."""

import secrets
from cryptography.fernet import Fernet

fernet_key = Fernet.generate_key().decode()
jwt_secret = secrets.token_urlsafe(48)

env = f"""# Generated by scripts/generate_env.py
DATABASE_URL=sqlite+aiosqlite:///./eve_dev.db
REDIS_URL=redis://localhost:6379/0

WALLET_ENCRYPTION_KEY={fernet_key}
JWT_SECRET={jwt_secret}

X_CLIENT_ID=
X_CLIENT_SECRET=
X_REDIRECT_URI=http://localhost:8000/v1/auth/x/callback

SOLANA_RPC_URL=https://api.mainnet-beta.solana.com

EXCESS_PROFIT_THRESHOLD_SOL=0.05
MAX_BUYBACK_SOL=1.0
RESERVE_SOL=0.01
"""

with open(".env", "w") as f:
    f.write(env)

print("Created .env with fresh keys")
print(f"  WALLET_ENCRYPTION_KEY={fernet_key[:20]}...")
print(f"  JWT_SECRET={jwt_secret[:20]}...")
